hojunyun-dev/Eat_Together

src/main/java/com/example/eat_together/domain/user/controller/UserController.java
src/main/java/com/example/eat_together/domain/user/dto/request/UserRequestDto.java
src/main/java/com/example/eat_together/domain/user/dto/response/UserResponseDto.java
src/main/java/com/example/eat_together/domain/user/entity/User.java
src/main/java/com/example/eat_together/domain/user/entity/UserRole.java
src/main/java/com/example/eat_together/domain/user/repository/UserRepository.java
src/main/java/com/example/eat_together/domain/user/service/UserService.java
src/main/java/com/example/eat_together/user/controller/UserController.java
src/main/java/com/example/eat_together/user/dto/request/UserRequestDto.java
src/main/java/com/example/eat_together/user/dto/response/UserResponseDto.java
src/main/java/com/example/eat_together/user/repository/UserRepository.java
src/main/java/com/example/eat_together/user/service/UserService.java

feat: 도메인 전체 구조 및 파일 추가

---

src/main/java/com/example/eat_together/domain/order/controller/OrderController.java
src/main/java/com/example/eat_together/domain/order/entity/Order.java
src/main/java/com/example/eat_together/domain/order/entity/OrderStatus.java
src/main/java/com/example/eat_together/domain/order/repository/OrderRepository.java
src/main/java/com/example/eat_together/domain/order/service/OrderService.java

#7
- OrderController, Order 엔티티, OrderService, OrderRepository 클래스 생성
- OrderStatus enum 클래스 생성(주문완료, 배달중, 배달완료)

Order 도메인 기본 구조 설정

---

src/main/java/com/example/eat_together/domain/rider/controller/RiderController.java
src/main/java/com/example/eat_together/domain/rider/dto/request/RiderRequestDto.java
src/main/java/com/example/eat_together/domain/rider/dto/response/RiderResponseDto.java
src/main/java/com/example/eat_together/domain/rider/entity/Rider.java
src/main/java/com/example/eat_together/domain/rider/repository/RiderRepository.java
src/main/java/com/example/eat_together/domain/rider/service/RiderService.java

#11 
- Entity 생성 (Soft Delete 포함)
- Repository 커스텀 메서드 정의
- Service 기본 등록/조회 로직 작성
- Controller 기본 API 구성
- DTO 틀 생성 (필드 없음)

feat: Rider 도메인 기본 구조 설계

---

src/main/java/com/example/eat_together/domain/user/controller/UserController.java
src/main/java/com/example/eat_together/domain/user/dto/request/SignupRequestDto.java
src/main/java/com/example/eat_together/domain/user/dto/request/UpdateUserInfoRequestDto.java
src/main/java/com/example/eat_together/domain/user/dto/response/UserResponseDto.java
src/main/java/com/example/eat_together/domain/user/entity/User.java
src/main/java/com/example/eat_together/domain/user/enums/MessageEnum.java
src/main/java/com/example/eat_together/domain/user/service/AuthService.java
src/main/java/com/example/eat_together/domain/user/service/UserService.java
src/main/java/com/example/eat_together/global/dto/ApiResponse.java
src/main/java/com/example/eat_together/global/entity/BaseTimeEntity.java
src/main/java/com/example/eat_together/global/exception/ErrorCode.java
src/main/java/com/example/eat_together/global/util/JwtAuthenticationFilter.java
src/main/java/com/example/eat_together/global/util/JwtUtil.java
src/main/resources/application.yml

#19 
User 비밀번호 변경 API & User 개인 정보(email, nickname, name) 변경 API

Feat : User 비밀번호 변경 & 개인정보 변경 API ( #19 )

---

src/main/java/com/example/eat_together/domain/chat/chatEnum/ChatResponse.java
src/main/java/com/example/eat_together/domain/chat/controller/ChatController.java
src/main/java/com/example/eat_together/domain/chat/entity/ChatGroup.java
src/main/java/com/example/eat_together/domain/chat/entity/ChatRoom.java
src/main/java/com/example/eat_together/domain/chat/service/ChatService.java
src/main/java/com/example/eat_together/domain/user/entity/User.java
src/main/java/com/example/eat_together/global/entity/BaseTimeEntity.java
src/main/java/com/example/eat_together/global/exception/ErrorCode.java

#31 
- 채팅방 입장 시 멤버 추가
- 이미 저장되어 있으면 미추가

[feature] 채팅방 입장 시 멤버 추가(#31)

---

src/main/java/com/example/eat_together/domain/user/controller/AuthController.java
src/main/java/com/example/eat_together/domain/user/controller/UserController.java
src/main/java/com/example/eat_together/domain/user/entity/User.java
src/main/java/com/example/eat_together/domain/user/enums/MessageEnum.java
src/main/java/com/example/eat_together/global/exception/ErrorCode.java

#37 
관리자 계정 삭제 불가 처리 및 Controller 출력값 변경

Feat : 관리자 계정 삭제 불가 처리

---

src/main/java/com/example/eat_together/domain/cart/repository/CartRepository.java
src/main/java/com/example/eat_together/domain/cart/service/CartService.java
src/main/java/com/example/eat_together/domain/user/controller/AdminAccountInitializer.java
src/main/java/com/example/eat_together/domain/user/controller/UserController.java
src/main/java/com/example/eat_together/domain/user/dto/request/ChangePasswordRequestDto.java
src/main/java/com/example/eat_together/domain/user/dto/request/LoginRequestDto.java
src/main/java/com/example/eat_together/domain/user/dto/request/PasswordRequestDto.java
src/main/java/com/example/eat_together/domain/user/dto/request/SignupRequestDto.java
src/main/java/com/example/eat_together/domain/user/service/UserService.java
src/main/java/com/example/eat_together/global/config/SecurityConfig.java

#46 
유저 전체 조회시 페이징 기능 추가
Request에 제약조건들 추가

Feat : 유저 전체 조회시 페이징 기능 추가 #46

---

src/main/java/com/example/eat_together/domain/chat/controller/ChatController.java
src/main/java/com/example/eat_together/domain/chat/entity/ChatMessage.java
src/main/java/com/example/eat_together/domain/chat/service/ChatService.java
src/main/java/com/example/eat_together/domain/user/entity/User.java
src/main/java/com/example/eat_together/global/config/SecurityConfig.java
src/main/java/com/example/eat_together/global/config/WebSocketConfig.java
src/main/java/com/example/eat_together/global/websocket/ChatMessageHandler.java
src/main/java/com/example/eat_together/global/websocket/WebSocketInterceptor.java

#56 
- 실시간 채팅을 구현했습니다. 아직 사용자 아이디를 저장하지 않아 익명 채팅과 같은 기능으로 제공됩니다.

[feat] 실시간 채팅 구현(#56)

---

src/main/java/com/example/eat_together/domain/store/controller/StoreController.java
src/main/java/com/example/eat_together/domain/store/dto/request/StoreRequestDto.java
src/main/java/com/example/eat_together/domain/store/repository/StoreRepository.java
src/main/java/com/example/eat_together/domain/store/service/StoreService.java
src/main/java/com/example/eat_together/global/exception/ErrorCode.java

#63 
- 오픈 시간이 종료 시간보다 같거나 늦은 경우 예외처리
- 매장 생성 시 카테고리가 카테고리 목록에 없는 경우 예외처리
- 한 명의 점주가 동일한 이름의 매장을 소유하고 있을 때 중복 등록 불가하도록 예외처리
- 매장 소유자가 아닌 사용자가 수정, 삭제를 할 수 없도록 예외처리
- 검색 결과가 비어있는 경우 예외처리

[feature] Store 도메인 예외처리 추가 (#63)

---

src/main/java/com/example/eat_together/domain/cart/controller/CartController.java
src/main/java/com/example/eat_together/domain/cart/dto/CartResponseDto.java
src/main/java/com/example/eat_together/domain/cart/service/CartService.java

#65 
- `CartController`의 메뉴 추가 API 경로 수정
- 관련 서비스 메서드 수정

[refactor] 장바구니 메뉴 추가 API 경로 및 메서드 수정

---

.gitignore
settings.gradle
src/main/java/com/example/eat_together/domain/rider/controller/RiderController.java
src/main/java/com/example/eat_together/domain/rider/dto/request/RiderRequestDto.java
src/main/java/com/example/eat_together/domain/rider/dto/response/RiderResponseDto.java
src/main/java/com/example/eat_together/domain/rider/entity/Rider.java
src/main/java/com/example/eat_together/domain/rider/service/RiderService.java

feat: 라이더 도메인 리팩토링 및 연관관계 수정

---

src/main/java/com/example/eat_together/domain/user/controller/AuthController.java
src/main/java/com/example/eat_together/domain/user/controller/UserController.java
src/main/java/com/example/eat_together/domain/user/dto/request/ReissueRequestDto.java
src/main/java/com/example/eat_together/domain/user/entity/User.java
src/main/java/com/example/eat_together/domain/user/enums/MessageEnum.java
src/main/java/com/example/eat_together/domain/user/service/AuthService.java
src/main/java/com/example/eat_together/domain/user/service/UserService.java
src/main/java/com/example/eat_together/global/config/SecurityConfig.java
src/main/java/com/example/eat_together/global/exception/ErrorCode.java
src/main/java/com/example/eat_together/global/util/JwtAuthenticationFilter.java
src/main/java/com/example/eat_together/global/util/JwtUtil.java

#77 
Access Token 만료 시 재발급 API 추가
삭제된 유저 복구 API 추가 
패키지에 맞게 리펙토링

Feat : API 추가 및 패키지에 맞게 리펙토링

---

src/main/java/com/example/eat_together/domain/rider/controller/RiderController.java
src/main/java/com/example/eat_together/domain/rider/dto/request/RiderStatusRequestDto.java
src/main/java/com/example/eat_together/domain/rider/dto/response/RiderResponseDto.java
src/main/java/com/example/eat_together/domain/rider/entity/Rider.java
src/main/java/com/example/eat_together/domain/rider/riderEnum/RiderResponse.java
src/main/java/com/example/eat_together/domain/rider/riderEnum/RiderStatus.java
src/main/java/com/example/eat_together/domain/rider/service/RiderService.java
src/main/java/com/example/eat_together/global/dto/ApiResponse.java

#76 
-상태 변경용 RequestDto 및 Enum 클래스 추가
-RiderController, RiderService 로직 수정
-관련 DTO 및 응답 형식 수정

feat: 라이더 배달 상태 변경 기능 구현

---

src/main/java/com/example/eat_together/domain/store/controller/StoreController.java
src/main/java/com/example/eat_together/domain/store/service/StoreService.java

#89 
- Store 생성 시 user.setRole을 통해 OWNER 권한 부여
- Controller에서 OWNER만 사용 가능한 기능을 선정하여, @PreAuthorize("hasRole('OWNER')")로 제한

[feature] 매장 생성 시 사용자에게 권한 부여 및, OWNER 권한을 가진 사용자만 이용 가능한 기능 제한 (#89)

---

src/main/java/com/example/eat_together/domain/chat/dto/ChatMessageResponseDto.java
src/main/java/com/example/eat_together/domain/chat/entity/ChatMessage.java

-
roomId와 userId가 메세지 내역 조회 시 바뀌어 나오는 문제를 발견했고 수정했습니다.

[refactor] roomId userId 바뀐 오류 해결

---

src/main/java/com/example/eat_together/domain/rider/controller/RiderController.java
src/main/java/com/example/eat_together/domain/rider/dto/request/RiderRequestDto.java
src/main/java/com/example/eat_together/domain/rider/dto/response/RiderResponseDto.java
src/main/java/com/example/eat_together/domain/rider/entity/Rider.java
src/main/java/com/example/eat_together/domain/rider/service/RiderService.java

#94 
-Rider 엔티티에 openTime, closeTime(LocalTime) 추가
- RiderService 로직 전반 수정 (생성, 수정, 조회)

feat: 라이더 openTime / closeTime 필드 추가 및 전체 로직 반영

---

src/main/java/com/example/eat_together/domain/order/dto/request/OrderStatusUpdateRequestDto.java
src/test/java/com/example/eat_together/domain/cart/fixture/CartTestFixture.java
src/test/java/com/example/eat_together/domain/order/fixture/OrderTestFixture.java
src/test/java/com/example/eat_together/domain/order/service/OrderServiceTest.java

#110 
- OrderServiceTest 코드 개선
- 테스트용 OrderTestFixture, CartTestFixture 추가

test: OrderServiceTest 코드 개선 및 테스트용 OrderTestFixture, CartTestFixture 추가(#110)

---

src/main/java/com/example/eat_together/domain/user/controller/UserController.java
src/main/java/com/example/eat_together/domain/user/dto/request/ChangePasswordRequestDto.java
src/main/java/com/example/eat_together/domain/user/dto/request/LoginRequestDto.java
src/main/java/com/example/eat_together/domain/user/dto/request/PasswordRequestDto.java
src/main/java/com/example/eat_together/domain/user/dto/request/ReissueRequestDto.java
src/main/java/com/example/eat_together/domain/user/dto/request/SignupRequestDto.java
src/main/java/com/example/eat_together/domain/user/dto/request/UpdateUserInfoRequestDto.java
src/main/java/com/example/eat_together/domain/user/service/UserService.java

#112 
기본 생성자를 만들지 않은 Request는 역직렬화 오류 발생
@NoArgsConstructor 사용으로 해결

fix : Request 오류 해결 ( #112 )

---

src/main/java/com/example/eat_together/domain/user/controller/UserController.java
src/main/java/com/example/eat_together/domain/user/dto/request/UserSearchRequestDto.java
src/main/java/com/example/eat_together/domain/user/dto/response/UserInfoResponseDto.java
src/main/java/com/example/eat_together/domain/user/repository/UserRepository.java
src/main/java/com/example/eat_together/domain/user/service/UserService.java
src/main/java/com/example/eat_together/global/exception/ErrorCode.java

#116 
User 권한을 가진 사람도 이름, 닉네임으로 검색 기능 추가 
중복된 이름, 닉네임이 있을 시 모두 출력

feat : 닉네임,이름으로 검색 기능 추가 ( #116)

---

src/main/java/com/example/eat_together/domain/chat/chatEnum/ChatGroupStatus.java
src/main/java/com/example/eat_together/domain/chat/chatEnum/ChatResponse.java
src/main/java/com/example/eat_together/domain/chat/controller/ChatController.java
src/main/java/com/example/eat_together/domain/chat/dto/ChatGroupDto.java
src/main/java/com/example/eat_together/domain/chat/dto/ChatRoomDto.java
src/main/java/com/example/eat_together/domain/chat/entity/ChatGroup.java
src/main/java/com/example/eat_together/domain/chat/entity/ChatRoomUser.java
src/main/java/com/example/eat_together/domain/chat/service/ChatService.java
src/main/java/com/example/eat_together/domain/chat/service/ChatUtil.java
src/main/java/com/example/eat_together/global/exception/ErrorCode.java
src/main/java/com/example/eat_together/global/websocket/ChatMessageHandler.java

Resolves: #118
#118 
- ChatGroupStatus 기본값 및 채팅방 멤버 수에 따른 상태 변경
- 채팅방 멤버 아닌 경우 채팅방 접속 제한
- ChatService와 ChatMessageHandler에서 사용하던 활용 메서드를 ChatUtil 클래스로 분리

Feat: 상황에 따른 채팅방 상태 변경, 채팅방멤버 아닐 시 접속 제한(#118)

---

src/main/java/com/example/eat_together/domain/chat/chatEnum/ChatResponse.java
src/main/java/com/example/eat_together/domain/chat/chatEnum/MemberRole.java
src/main/java/com/example/eat_together/domain/chat/controller/ChatController.java
src/main/java/com/example/eat_together/domain/chat/entity/ChatRoomUser.java
src/main/java/com/example/eat_together/domain/chat/service/ChatService.java
src/main/java/com/example/eat_together/domain/chat/service/ChatUtil.java
src/main/java/com/example/eat_together/global/exception/ErrorCode.java
src/main/java/com/example/eat_together/global/websocket/ChatMessageHandler.java

#120 
- 채팅 그룹 멤버 역할 컬럼 추가
- host 역할 가진 사람만 해당 채팅 그룹 삭제 가능하도록 기능 구현

Feat: 채팅그룹 멤버 역할 컬럼 추가 및 host만 채팅 그룹 삭제 가능하도록 구현(#120)

---

src/main/java/com/example/eat_together/domain/order/repository/OrderRepository.java
src/main/java/com/example/eat_together/domain/rider/service/RiderService.java

#109 
- Rider 상태 변경 시 Order 상태 자동 동기화 로직 추가
- RiderStatus와 OrderStatus enum 매핑 처리

feat: Rider 상태 변경 시 Order 상태 동기화 기능 구현

---

src/main/java/com/example/eat_together/domain/order/repository/OrderRepositoryCustomImpl.java

#151 
- 주문 내역 페이징 조회에 인덱스 적용하여 성능 개선

refactor: 주문 내역 페이징 조회에 인덱스 적용하여 성능 개선(#151)

---

.gitignore
Dockerfile.elasticsearch
docker-compose.yml
src/main/resources/application.yml

#170 
docker-compose에 엘라스틱서치 추가

feat : docker-compose에 엘라스틱서치 추가 ( #170 )

---

build.gradle
src/main/java/com/example/eat_together/domain/order/repository/OrderRepository.java
src/main/java/com/example/eat_together/domain/order/service/OrderService.java
src/main/java/com/example/eat_together/domain/payment/repository/PaymentRepository.java
src/main/java/com/example/eat_together/domain/payment/service/PaymentService.java
src/main/java/com/example/eat_together/global/redis/RedissonConfig.java
src/main/java/com/example/eat_together/global/redis/service/LockService.java

#179 
- 주문 생성 부분에 적용한 비관적락을 Redis 락으로 변경하였습니다.
- 결제 생성에 Redis 락을 적용하였습니다.

feat: 주문 생성 비관적락 -> Redis 락 변경 / 결제 생성 Redis 락 적용(#179)
